security:
  basic:
    enabled: false

hystrix:
  suffixUrl: ${PC_HYSTRIX_SUFFIX_URL:/hystrix/hystrix.stream}

discoveryService:
  fixedDelayMs: ${PC_DISCOVERY_SERVICE_FIXED_DELAY_MS:10000}
  exclude: consul, application

httpClient:
  retry: 3
  socketTimeoutMs: 10000
  connectTimeoutMs: 10000
  maxConnPerRoute: 100
  maxConnTotal: 200

influxDB:
  url: ${PC_INFLUXDB_URL:http://localhost:8086}
  username: ${PC_INFLUXDB_USERNAME:root}
  password: ${PC_INFLUXDB_PASSWORD:root}
  dbName: ${PC_INFLUXDB_DBNAME:hystrix}

debug: false
spring:
  main:
    web-environment: false
  cloud:
    consul:
      discovery:
        enabled: true
      enabled: true
