security:
  basic:
    enabled: false

hystrix:
  subscriptions:
    -
      serviceId: myService
      url: "http://localhost:8080/hystrix.stream"

httpClient:
  retry: 3
  socketTimeoutMs: 10000
  connectTimeoutMs: 10000
  maxConnPerRoute: 100
  maxConnTotal: 200

influxDB:
  url: ${INFLUXDB_URL:http://localhost:8086}
  username: ${INFLUXDB_USERNAME:root}
  password: ${INFLUXDB_PASSWORD:root}
  dbName: ${INFLUXDB_DBNAME:hystrix}

debug: false
spring:
  application:
    name: hystrix-collector
  main:
    web-environment: false